# Generated by Django 3.0.4 on 2020-03-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Earth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('earth_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid.Earth')),
                ('casesToday', models.IntegerField()),
                ('deathsToday', models.IntegerField()),
                ('active', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('casesPerMillion', models.IntegerField()),
                ('deathsPerMillion', models.IntegerField()),
                ('countryInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='covid.CountryInfo')),
            ],
            bases=('covid.earth',),
        ),
    ]
