# Generated by Django 3.0.4 on 2020-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryinfo',
            name='flag',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='iso2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='iso3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='countryinfo',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
